language: r
sudo: required
warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr); codecov()'

r_github_packages:
  - hadley/testthat # for skip_if_not_installed
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T233KRG4R'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
