language: r
sudo: required
warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr); codecov()'

r_github_packages:
  - hadley/testthat # for skip_if_not_installed

r_github_packages:
  - hadley/testthat # for skip_if_not_installed

r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
