---
title: "Using heatmaply with biological data (mutational and gene expression data)"
date: "`r Sys.Date()`"
author: "Alan O'Callaghan"
output:
  html_document:
    self_contained: yes
    toc: true    
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Using heatmaply with biological data}
-->


```{r, echo = FALSE, message = FALSE}
library(heatmaply)
library(knitr)
knitr::opts_chunk$set(
   # cache = TRUE,
   dpi = 60,
  comment = "#>",
  tidy = FALSE)

```
**Author**: Alan O'Callaghan (alan.b.ocallaghan@gmail.com)




Introduction
============



Required packages
=================


heatmaply workflow
==================
```{r}
cor_mat <- cor(raw_pam50_expression)
dimnames(cor_mat) <- NULL


heatmaply(cor_mat, 
    main = "Count data correlation",
    plot_method = "plotly",
    col_side_colors=tcga_brca_clinical)

```


```{r}
cor_mat <- cor(log2(raw_pam50_expression + 0.5))
dimnames(cor_mat) <- NULL


heatmaply(cor_mat, 
    main = "log2 Count data correlation",
    plot_method = "plotly",
    col_side_colors=tcga_brca_clinical)

```

voom explanation

```{r}

cor_mat <- cor(voomed_pam50_expression)
dimnames(cor_mat) <- NULL


heatmaply(cor_mat, 
    main = "log2 cpm data correlation",
    plot_method = "plotly",
    col_side_colors=tcga_brca_clinical)



heatmaply(
    log2(raw_pam50_expression + 0.5) - rowMedians(log2(raw_pam50_expression + 0.5)),
    col_side_colors=tcga_brca_clinical)


heatmaply(voomed_pam50_expression - rowMedians(voomed_pam50_expression),
    col_side_colors=tcga_brca_clinical)

    
heatmaply(voomed_pam50_expression, scale = "row",
    col_side_colors=tcga_brca_clinical)

```

